### ISSUE TITLE
UI slowness with many configs

### ISSUE THREAD

**Issue by belvedere-trading** [ConfigHubPub/ConfigHubPlatform#6] opened 2017-04-28 17:28 UTC
Hi there,

We're currently experience a significant usability issue with the UI after loading in many configurations (~1000). When opening the web page, everything essentially locks up for more than a minute while it attempts to show all configs for the all star context.

Pulls seem to be unaffected by this problem (they return almost instantly), so this is probably a UI issue only.

I would call this a high priority - our developers can't really work with the system in its current state until this is resolved.

**Comment by edoarsla** [comment] 2017-04-28 17:55
1. Which version are you running
2. Are there many properties that are either JSON or Code type
3. Are there keys that have a large number of values assigned to them - (50+)

We test with repositories that have 15k+ properties - I am certain this is not a volume of properties issue.  However, we did see degradation of rendering for JSON and Code datatypes - because of the syntax highlighting - this could be a culprit.

Second thought is that - pagination is based on key (not values).  Since you’re *not* specifying context, this would mean that for each given key, all values are returned.  So, if there are keys that have large number of values assigned to them (and further more of those are JSON or Code type), this would be large render.

At the bottom of the configuration page, you’ll find the dropdown for number of keys to show - please select 10, as this will improve the rendering speed while we hunt for the cause.

**Comment by edoarsla** [comment] 2017-04-28 17:57
Oh, and which browser are you using - so we can try and replicate?

**Comment by belvedere-trading** [comment] 2017-04-28 18:15
1. Latest
2. Not currently, the majority (perhaps all) are simple atoms.
3. Yes, definitely. Almost every key has a large number of values associated with it.
4. Chrome, latest version.

It sounds like your second thought has some merit to me. We would just say not to specify such general contexts, but the page defaults to all star so we can't really do that unfortunately.

**Comment by edoarsla** [comment] 2017-05-02 13:33
This is resolved as of v1.3.4.
Enabled pagination for values per key and optimized rendering code.

**Closed by edoarsla** 2017-05-02 13:33 UTC

**Comment by belvedere-trading** [comment] 2017-05-02 13:52
Thanks for the quick fix!
