### ISSUE TITLE
File saving bug with preview

### ISSUE THREAD

**Issue by belvedere-trading** [ConfigHubPub/ConfigHubPlatform#17] opened 2017-06-05 13:37 UTC
Hey there,

I'm not 100% sure how to reproduce this issue reliably, but I've definitely noticed that there is some kind of (I'm assuming UI-side) issue that causes changes to files to not be saved on occasion. If I make changes to a file, preview the file, then save the changes, somewhere around 50% of the time the changes will not be persisted. I'll try to update with more information if I'm able to reproduce this more reliably.

Thanks,
Jordan

**Comment by belvedere-trading** [comment] 2017-06-05 13:50
This bug could actually exist somehow on the backend too - I think I was just in a situation where the file shown in the UI wasn't the same as the file being returned by the backend. Not really sure if that would be possible; re-saving the file that I could see in the UI resolved the issues.

**Comment by edoarsla** [comment] 2017-06-05 13:56
Both the UI and the API go through the same channel, so there should not be a difference there.
Which ConfigHub version are you on, and which browser are you using?

**Comment by edoarsla** [comment] 2017-06-05 14:21
I am not able to reproduce.  I tried many combinations of preview, click-away save prompt, and just saving, all while validating through the PULL request.

I'm running v1.4, using Safari on Mac.

**Comment by belvedere-trading** [comment] 2017-06-05 14:24
The instance I'm using is still on 1.3.3, using Chrome. We'll get this instance upgraded today and I'll get back to you if I see if again. Thanks for looking into it.

**Comment by edoarsla** [comment] 2017-06-05 14:31
There's no question that instance had several issues related to files.  That was a regression issue.
And it makes perfect sense in what you're claiming - one of the bugs was that a file could be saved with the same context as existing file - new file would be ignored, and the "old" file is returned by the API request.

Once you upgrade, you will probably see several versions of the same file/context (as you were testing).  You can delete all unwanted, and keep just one.

**Comment by edoarsla** [comment] 2017-06-08 02:53
Fixed in v1.3.4

**Closed by edoarsla** 2017-06-08 02:53 UTC
